### PR TITLE
Prepare for drift v2

### PR DESCRIPTION
**Pull request by NicolaVerbeeck**
Waiting for drift v2 to be released. 

See https://github.com/simolus3/drift/issues/1158

### CODE REVIEW

**Comment by frankvollebregt** [comment]
I just upgraded `drift` and came here to ask for an update to this package as well, but you were already on it I see.

When I try to use the `feature/driftv2` branch as a dependency override in my app, `pub get` fails with the following message:
```
Because every version of drift_local_storage_inspector from git depends on drift ^1.4.0 and MY_APP_NAME depends on drift ^2.0.0, drift_local_storage_inspector from git is forbidden.
So, because MY_APP_NAME depends on drift_local_storage_inspector from git, version solving failed.
pub get failed (1; So, because MY_APP_NAME depends on drift_local_storage_inspector from git, version solving failed.)
```
I guess you'll need to update the version of the drift dependency to `^2.0.0` in `pubspec.yaml` before merging this PR.

Thanks for keeping the package up-to-date :)

**Comment by NicolaVerbeeck** [comment]
That's why this PR has not been merged 😊. Packages should never depend on
other packages by git urls, that won't work. as soon as drift v2 is
released to pub dev I will patch this PR and release it officially. If you
really need to start using drift v2 right now, you'll have to override all
dependencies on drift (see example)

**Comment by frankvollebregt** [comment]
Thanks for the response. Drift `v2.0.0` was actually released yesterday (and `v2.0.1` as a first patch earlier today), which is why I ran into the issue in the first place. I'll add this package back into my app once this PR is released!

**Comment by NicolaVerbeeck** [comment]
@frankvollebregt 0.3.0 has been released to pub dev which supports drift v2

**Pull request merged**
